<<<<<<< HEAD
# Copyright (C) 2014 The CyanogenMod Project
=======
# Copyright (C) 2015 The CyanogenMod Project
>>>>>>> 4de6ff60557f55d560ef1b532ce7d501b194e7bc
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
<<<<<<< HEAD
#      http://www.apache.org/licenses/LICENSE-2.0
=======
# http://www.apache.org/licenses/LICENSE-2.0
>>>>>>> 4de6ff60557f55d560ef1b532ce7d501b194e7bc
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This file is generated by device/lge/l01f/setup-makefiles.sh

<<<<<<< HEAD
# Live wallpaper packages
PRODUCT_PACKAGES := \
    LiveWallpapers \
    LiveWallpapersPicker \
    MagicSmokeWallpapers \
    VisualizationWallpapers \
    librs_jni

# Publish that we support the live wallpaper feature.
PRODUCT_COPY_FILES := \
    packages/wallpapers/LivePicker/android.software.live_wallpaper.xml:/system/etc/permissions/android.software.live_wallpaper.xml

# Pick up overlay for features that depend on non-open-source files
DEVICE_PACKAGE_OVERLAYS := vendor/lge/l01f/overlay

=======
>>>>>>> 4de6ff60557f55d560ef1b532ce7d501b194e7bc
$(call inherit-product, vendor/lge/l01f/l01f-vendor-blobs.mk)
